### PR TITLE
feat: add meta to jdef output

### PR DESCRIPTION
**Pull request by joshuaslate**
This is one of the changes we discussed on Friday.

### CODE REVIEW

**Review by dan9186 — APPROVED** [review]

**Comment by dan9186** [comment]
@daemonl how do we go about generating when putting up something like this? `buf generate` I'm assuming was intentionally broken by putting it to `v2`, and when trying to use `j5 generate` it throws an error.

**Comment by daemonl** [comment]
`buf generate` should work with v2, that's a legit update, we are not yet at the milestone of `j5 generate`. 
You'll need to install the latest version of all the plugins tho, so if you want to flick them to me I can generate for now

**Comment by joshuaslate** [comment]
@daemonl, I ran buf generate here and it seems to have worked. If you wouldn't mind running it if I'm behind on versions, I'd appreciate it.

Dan and I have been discussing ways to make more codegen possible on my end and to improve type safety on the request parameters (query object). This would include things like:
- Adding a field for sortable fields to the request schema `x-sortable-fields: string[]`
- Adding a field for filterable fields to the request schema `x-filterable-fields: { name: string; min?: number; max?: number; }[]`

These would enable me to add type-safety on the queries, so there'd be less guess & check and it'd be less error-prone.

Then on the state entity schemas:
- Adding `x-primary-key: string`
- Adding `x-foreign-keys: { field: string; ref: { $ref: ref to another schema } }[]`

This would allow me to build normalization models, which I'm using to power the caching on the frontend, so I'd basically be able to generate _all_ of the data fetching & caching code with these two fields present.

--

Dan mentioned that you've been working to do some untangling of psm & j5 (if I understood correctly), but adding these would re-introduce some of that, I believe. Do you have any ideas for how this could best be approached?

**Comment by daemonl** [comment]
Have a look https://github.com/pentops/j5/issues/64 for the broader changes.

Are you using the JSON Schema stuff as actual JSON schema? Or can we just define our own? Would be nice to stop worrying about the `x-` names and just define this in our own way, but if you are using tools which need it that way we can keep going this way.

**Comment by joshuaslate** [comment]
I'll take a look at #64. We can define our own, I'm manually parsing everything anyway. Any changes will impact API documentation generation and codegen, but if it's just shifting around key names, the updates would be pretty quick and easy.

**Pull request merged**
